/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HyrRouteImport } from './routes/hyr'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as PaneliRouteImport } from './routes/paneli'
import { Route as RegjistrohuRouteImport } from './routes/regjistrohu'
import { Route as RegjistrohuFizioterapeutRouteImport } from './routes/regjistrohu-fizioterapeut'
import { Route as FizioterapeutetIndexRouteImport } from './routes/fizioterapeutet.index'
import { Route as FizioterapeutetQytetiRouteImport } from './routes/fizioterapeutet.$qyteti'
import { Route as LlogariaIndexRouteImport } from './routes/llogaria.index'
import { Route as LlogariaTerminetRouteImport } from './routes/llogaria.terminet'
import { Route as RezervoSlugRouteImport } from './routes/rezervo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HyrRoute = HyrRouteImport.update({
  id: '/hyr',
  path: '/hyr',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const PaneliRoute = PaneliRouteImport.update({
  id: '/paneli',
  path: '/paneli',
  getParentRoute: () => rootRouteImport,
} as any)
const RegjistrohuRoute = RegjistrohuRouteImport.update({
  id: '/regjistrohu',
  path: '/regjistrohu',
  getParentRoute: () => rootRouteImport,
} as any)
const RegjistrohuFizioterapeutRoute =
  RegjistrohuFizioterapeutRouteImport.update({
    id: '/regjistrohu-fizioterapeut',
    path: '/regjistrohu-fizioterapeut',
    getParentRoute: () => rootRouteImport,
  } as any)
const FizioterapeutetIndexRoute = FizioterapeutetIndexRouteImport.update({
  id: '/fizioterapeutet/',
  path: '/fizioterapeutet/',
  getParentRoute: () => rootRouteImport,
} as any)
const FizioterapeutetQytetiRoute = FizioterapeutetQytetiRouteImport.update({
  id: '/fizioterapeutet/$qyteti',
  path: '/fizioterapeutet/$qyteti',
  getParentRoute: () => rootRouteImport,
} as any)
const LlogariaIndexRoute = LlogariaIndexRouteImport.update({
  id: '/llogaria/',
  path: '/llogaria/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlogariaTerminetRoute = LlogariaTerminetRouteImport.update({
  id: '/llogaria/terminet',
  path: '/llogaria/terminet',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervoSlugRoute = RezervoSlugRouteImport.update({
  id: '/rezervo/$slug',
  path: '/rezervo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/hyr': typeof HyrRoute
  '/kontakti': typeof KontaktiRoute
  '/paneli': typeof PaneliRoute
  '/regjistrohu': typeof RegjistrohuRoute
  '/regjistrohu-fizioterapeut': typeof RegjistrohuFizioterapeutRoute
  '/fizioterapeutet/$qyteti': typeof FizioterapeutetQytetiRoute
  '/llogaria/terminet': typeof LlogariaTerminetRoute
  '/rezervo/$slug': typeof RezervoSlugRoute
  '/fizioterapeutet/': typeof FizioterapeutetIndexRoute
  '/llogaria/': typeof LlogariaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/hyr': typeof HyrRoute
  '/kontakti': typeof KontaktiRoute
  '/paneli': typeof PaneliRoute
  '/regjistrohu': typeof RegjistrohuRoute
  '/regjistrohu-fizioterapeut': typeof RegjistrohuFizioterapeutRoute
  '/fizioterapeutet/$qyteti': typeof FizioterapeutetQytetiRoute
  '/llogaria/terminet': typeof LlogariaTerminetRoute
  '/rezervo/$slug': typeof RezervoSlugRoute
  '/fizioterapeutet': typeof FizioterapeutetIndexRoute
  '/llogaria': typeof LlogariaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/hyr': typeof HyrRoute
  '/kontakti': typeof KontaktiRoute
  '/paneli': typeof PaneliRoute
  '/regjistrohu': typeof RegjistrohuRoute
  '/regjistrohu-fizioterapeut': typeof RegjistrohuFizioterapeutRoute
  '/fizioterapeutet/$qyteti': typeof FizioterapeutetQytetiRoute
  '/llogaria/terminet': typeof LlogariaTerminetRoute
  '/rezervo/$slug': typeof RezervoSlugRoute
  '/fizioterapeutet/': typeof FizioterapeutetIndexRoute
  '/llogaria/': typeof LlogariaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/hyr'
    | '/kontakti'
    | '/paneli'
    | '/regjistrohu'
    | '/regjistrohu-fizioterapeut'
    | '/fizioterapeutet/$qyteti'
    | '/llogaria/terminet'
    | '/rezervo/$slug'
    | '/fizioterapeutet/'
    | '/llogaria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/hyr'
    | '/kontakti'
    | '/paneli'
    | '/regjistrohu'
    | '/regjistrohu-fizioterapeut'
    | '/fizioterapeutet/$qyteti'
    | '/llogaria/terminet'
    | '/rezervo/$slug'
    | '/fizioterapeutet'
    | '/llogaria'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/hyr'
    | '/kontakti'
    | '/paneli'
    | '/regjistrohu'
    | '/regjistrohu-fizioterapeut'
    | '/fizioterapeutet/$qyteti'
    | '/llogaria/terminet'
    | '/rezervo/$slug'
    | '/fizioterapeutet/'
    | '/llogaria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  HyrRoute: typeof HyrRoute
  KontaktiRoute: typeof KontaktiRoute
  PaneliRoute: typeof PaneliRoute
  RegjistrohuRoute: typeof RegjistrohuRoute
  RegjistrohuFizioterapeutRoute: typeof RegjistrohuFizioterapeutRoute
  FizioterapeutetQytetiRoute: typeof FizioterapeutetQytetiRoute
  LlogariaTerminetRoute: typeof LlogariaTerminetRoute
  RezervoSlugRoute: typeof RezervoSlugRoute
  FizioterapeutetIndexRoute: typeof FizioterapeutetIndexRoute
  LlogariaIndexRoute: typeof LlogariaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyr': {
      id: '/hyr'
      path: '/hyr'
      fullPath: '/hyr'
      preLoaderRoute: typeof HyrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paneli': {
      id: '/paneli'
      path: '/paneli'
      fullPath: '/paneli'
      preLoaderRoute: typeof PaneliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regjistrohu': {
      id: '/regjistrohu'
      path: '/regjistrohu'
      fullPath: '/regjistrohu'
      preLoaderRoute: typeof RegjistrohuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regjistrohu-fizioterapeut': {
      id: '/regjistrohu-fizioterapeut'
      path: '/regjistrohu-fizioterapeut'
      fullPath: '/regjistrohu-fizioterapeut'
      preLoaderRoute: typeof RegjistrohuFizioterapeutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fizioterapeutet/': {
      id: '/fizioterapeutet/'
      path: '/fizioterapeutet'
      fullPath: '/fizioterapeutet/'
      preLoaderRoute: typeof FizioterapeutetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fizioterapeutet/$qyteti': {
      id: '/fizioterapeutet/$qyteti'
      path: '/fizioterapeutet/$qyteti'
      fullPath: '/fizioterapeutet/$qyteti'
      preLoaderRoute: typeof FizioterapeutetQytetiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llogaria/': {
      id: '/llogaria/'
      path: '/llogaria'
      fullPath: '/llogaria/'
      preLoaderRoute: typeof LlogariaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llogaria/terminet': {
      id: '/llogaria/terminet'
      path: '/llogaria/terminet'
      fullPath: '/llogaria/terminet'
      preLoaderRoute: typeof LlogariaTerminetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervo/$slug': {
      id: '/rezervo/$slug'
      path: '/rezervo/$slug'
      fullPath: '/rezervo/$slug'
      preLoaderRoute: typeof RezervoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  HyrRoute: HyrRoute,
  KontaktiRoute: KontaktiRoute,
  PaneliRoute: PaneliRoute,
  RegjistrohuRoute: RegjistrohuRoute,
  RegjistrohuFizioterapeutRoute: RegjistrohuFizioterapeutRoute,
  FizioterapeutetQytetiRoute: FizioterapeutetQytetiRoute,
  LlogariaTerminetRoute: LlogariaTerminetRoute,
  RezervoSlugRoute: RezervoSlugRoute,
  FizioterapeutetIndexRoute: FizioterapeutetIndexRoute,
  LlogariaIndexRoute: LlogariaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
